const btnEditProfile = document.querySelector('.profile__edit-button'),
      btnAddNewPlace = document.querySelector('.profile__add-button'),
      popupEditProfile = document.querySelector('.popup_profile'),
      btnCloseEditProfile = popupEditProfile.querySelector('.popup__close-button'),
      newPlacePopup = document.querySelector('.popup_new-place'),
      newPlacePopupCloseBtn = newPlacePopup.querySelector('.popup__close-button'),
      popupImage = document.querySelector('.popup_big-image'),
      popupImageCloseBtn = popupImage.querySelector('.popup__close-button'),
      cardTemplate = document.querySelector('#card-template').content,
      cardsContainer = document.querySelector('.cards-container'),
      formNewPlace = newPlacePopup.querySelector('.popup__form'),
      formEditProfile = popupEditProfile.querySelector('.popup__form'),
      inputUserName = formEditProfile.querySelector('input[name="user-name"]'),
      inputUserBio = formEditProfile.querySelector('input[name="user-bio"]'),
      namePlace = formNewPlace.querySelector('input[name="place-name"]'),
      linkPlace = formNewPlace.querySelector('input[name="place-link"]'),
      bigImage = document.querySelector('.popup__big-img'),
      popupImgDesc = document.querySelector('.popup__img-description'),
      titleProfile = document.querySelector('.profile__title'),
      descProfile = document.querySelector('.profile__description'),
      popups = document.querySelectorAll('.popup');

export {
  btnEditProfile,
  btnAddNewPlace,
  popupEditProfile,
  btnCloseEditProfile,
  newPlacePopup,
  newPlacePopupCloseBtn,
  popupImage,
  popupImageCloseBtn,
  cardTemplate,
  cardsContainer,
  formNewPlace,
  formEditProfile,
  inputUserName,
  inputUserBio,
  namePlace,
  linkPlace,
  bigImage,
  popupImgDesc,
  titleProfile,
  descProfile,
  popups
}
